// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50QtCc4WsIxBu171WBKDb9CSJb_gLnfg',
    appId: '1:631391826676:web:29325d1b960a5d887964a1',
    messagingSenderId: '631391826676',
    projectId: 'parkspace-b155d',
    authDomain: 'parkspace-b155d.firebaseapp.com',
    storageBucket: 'parkspace-b155d.appspot.com',
    measurementId: 'G-ZVTQ74MNQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4Sty0R2NF5rhBMsve_gQDC-5MbnYEk8',
    appId: '1:631391826676:android:75ebf27179e1b41d7964a1',
    messagingSenderId: '631391826676',
    projectId: 'parkspace-b155d',
    storageBucket: 'parkspace-b155d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJDEPxt54p8gBm4VXTCypTelMd7IKYkE',
    appId: '1:631391826676:ios:38d1f408f51440ee7964a1',
    messagingSenderId: '631391826676',
    projectId: 'parkspace-b155d',
    storageBucket: 'parkspace-b155d.appspot.com',
    iosClientId: '631391826676-u36gp8errbjcc5kd725u5ndjdpqlsgrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkspace',
  );
}
